### ISSUE TITLE
Section 7.10.2: `innererror` vs `details`

### ISSUE THREAD

**Issue by krishnand** [Microsoft/api-guidelines#185]
- Is the `innererror` vs `details` mutually exclusive? If they are, could we align on the naming convention - maybe just `innererrors`. If they are not mutually exclusive, could there be a case for it to be assigned under the `innererror` as a `details` list?
- If the `details` is expected to a top level attribute, would it be better if it is an object instead of an array? A suggestion would be for it to be an object containing a list of `innererror` objects,

**Comment by gareth-a-jones** [comment]
Theoretically they aren't mutually exclusive but in practice they have been.  One is for a drill down on specifics, and the other is for building composite errors, for example where there is a cascade failure underlying the operation, such as in a compiler.

Help me understand how an object containing an array rather than simply an array would make `details `any more useful or clearer?

**Comment by gareth-a-jones** [comment]
I'm going to close this Krishnan.  

In general, we're not going to take changes unless there is a substantial improvement for customers that would significantly outweigh the downside of services differing in small but unnecessary ways between Microsoft products.
