### ISSUE TITLE
Azure Guidelines: Include Error Codes as part of OpenAPI spec

### ISSUE THREAD

**Issue by markweitzel** [Microsoft/api-guidelines#261]
During one of the API reviews, a question came up regarding the inclusion of service error codes in the OpenAPI specification for a service. In the guidelines, we indicate that the "code" part of the error body IS part of the API contract. Given this, should we recommend that all "codes" be enumerated in the OpenAPI document? Does this impact the breaking change policy? 

```json
{
  "error": {
    "code": "InvalidPasswordFormat",
    "message": "Human-readable description",
    "target": "target of error",
    "innererror": {
      "code": "PasswordTooShort",
      "minLength": 6,
    }
  }
} 
```

**Comment by mikekistler** [comment]
This topic was discussed in the 7/2/2021 Azure API Stewardship reviewers meeting and we decided that including the error codes in the API definition is desirable _if_ it can be done efficiently and in a way that the docs team can consume it.  There is also some intersection here with the work that @tg-msft is doing on best practices for error handling in the SDKs.

I will work with @diberry and @tg-msft to explore alternatives on this and bring a recommendation back to the Azure API Stewardship team.

**Comment by mikekistler** [comment]
The Azure Storage services have documented their error codes in their public documentation:

https://docs.microsoft.com/en-us/rest/api/storageservices/status-and-error-codes2

Some observations:
- There are 43 “common” error codes — like “ResourceNotFound”, “InvalidInput”, “ServiceError” — that should probably be common across _all_ Azure services, not just the storage services.
- Some of these codes cover multiple conditions that are differentiated by the error message. E.g. there are 4 possible conditions/messages for “ServerBusy”.
- The public docs associate error codes with particular HTTP status codes, which might be hard to do if we moved to document these with “extensible enums” in the API definition (but maybe that’s okay).
- The Blob service adds another 71 error codes on top of the common 43 — 114 in total.

**Comment by mikekistler** [comment]
Other points to consider:

- If we chose to include the error codes in the API definition, we would almost certainly do this with an [“extensible enum”](https://github.com/Azure/autorest/tree/main/docs/extensions#x-ms-enum), so that we could include a description for each error code.
- But it is common practice to define the values of an extensible enum _twice_, once in the enum (since this is the standard place) and again the the `x-ms-enum` annotation.  Following that practice for error codes would lead to a lot of duplication.
- Also, there is no OpenAPI mechanism to “merge” values for an enum, so we couldn’t (in a standard way) define the common error codes in one place and just reference this from individual service docs.
- There are actually _two_ places in an error response that should contain the error code: the `code` field in the response body and the value of the `x-ms-error-code` response header.  We could make the error code its own definition and then $ref to it from both these places.  Or we could choose to only attach the codes to one of these — and then hopefully do it consistently.

**Comment by tg-msft** [comment]
A couple of notes from a quick discussion with @mikekistler today:

- Some services are already specifying the [entire list of error codes](https://github.com/Azure/azure-rest-api-specs/blob/storage-dataplane-preview/specification/storage/data-plane/Microsoft.BlobStorage/preview/2019-02-02/blob.json#L8586) which is generated into [an extensible enum](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.bloberrorcode?view=azure-dotnet) that we [recommend to customers for error handling](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/storage/Azure.Storage.Blobs#troubleshooting).  It is unfortunately not specified per-operation.
- We don't [document individual status codes](https://swagger.io/specification/v2/#responsesObject) in our specs today because [AutoRest](https://github.com/azure/autorest) does not deduplicate (i.e., even though the error model is the same, you'll end up with `N` copies of the parsing code).  Even if we fix this bug, we still do not have a way of specifying the error codes today.  We'll need a swagger extension to make that possible.
- We're considering additional swagger extensions for other work (see [slide 34 -- INTERNAL ONLY](https://microsoft-my.sharepoint.com/:p:/p/teglaza/EeTYvK4JCJNIjtA1BLufg34B4MROlR-kaUACj3HqXidpNQ?e=Resebh)) that we could decide to adopt and begin using before it's officially ready.  Otherwise we probably won't have a way to specify per-operation error codes this semester.
- Some services struggle with which error codes to specify and the [Storage Common error codes](https://docs.microsoft.com/en-us/rest/api/storageservices/common-rest-api-error-codes) might be a good starting point to recommend in a blog post.
- We should encourage services to send the error code back as an `x-ms-error-code` header in addition to following the [official error response](https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#7102-error-condition-responses) in their response body.  This enables clients to potentially retry operations in their pipeline without parsing the response body (which we'll probably never do within the pipeline).
