### ISSUE TITLE
Document whether service should include api-version in nextLink or Operation-Location

### ISSUE THREAD

**Issue by annelo-msft** [Microsoft/api-guidelines#371]
The Azure SDK arch board has decided SDKs will handle `api-version` in `nextLink` and `Operation-Location` as described in this issue: https://github.com/Azure/azure-sdk/issues/3817#issuecomment-1033226508

However, I believe it is still undocumented what services should actually implement, whether these should include `api-version` or not.  This issue tracks adding this guidance to the REST API guidelines.

**Comment by mikekistler** [comment]
PR #353 contains explicit guidance for the `Operation-Location` header returned by LROs:

>> ☑️ YOU SHOULD include an Operation-Location header in the response with the absolute URL of the status monitor for the operation, but do not include an api-version query parameter.

It is safe to exclude `api-version` for `Operation-Location` because, if the service follows the new LRO guidelines, the operation that this header references is clearly documented in the REST API definition and this definition will indicate that an api-version query parameter is required.

Unfortunately, the same is not true (currently) for `nextLink` in the response of a pageable operation. The `nextLink` property is supposed to be an "opaque" URI to the next page of results. So I believe that `api-version` should be included in the URI value of `nextLink`, and we should update the Azure REST API Guidelines to explicitly state this.

**Comment by mikekistler** [comment]
I discussed this issue with @JeffreyRichter and he (grudgingly) agreed that we should direct services to include the api-version in the `nextLink` property.

The Azure SDKs should replace the value of api-version with the one specified by the user, as [required in the Azure SDK Guidelines](https://azure.github.io/azure-sdk/general_design.html#:~:text=%E2%9C%85%20DO%20add%20or%20replace%20the%20api%2Dversion%20query%20parameter%20on%20any%20URI%20returned%20by%20the%20service%20e.g.%2C%20Operation%2DLocation%2C%20next%20page%20links%2C%20etc.%2C%20with%20the%20service%20version%20passed%20configured%20on%20the%20client.). 

I have assigned myself to this issue and will create a PR to add this explicit guidance soon.
