### ISSUE TITLE
Feedback on PATCH 

### ISSUE THREAD

**Issue by maerlin** [Microsoft/api-guidelines#66]
Unfortunately i did not see any [guidlines](https://github.com/Microsoft/api-guidelines/blob/master/Guidelines.md#742-patch), how one should remove any fielddata from an object using PATCH or PUT.

Should Patch only support additive, atomic modifications?

I did some research and found JSON MERGE PATCH
[JSON Merge Patch RFC ](https://tools.ietf.org/html/rfc7396)

>    PATCH /target HTTP/1.1
   Host: example.org
   Content-Type: application/merge-patch+json
   {
     "a":"z",
     "c": {
       "f": null
   }

Or there is another way, using the older [JSON PATCH RFC ](https://tools.ietf.org/html/rfc6902) 

>  [
     { "op": "remove", "path": "/a/b/c" },
     { "op": "add", "path": "/a/b/c", "value": [ "foo", "bar" ] },
     { "op": "replace", "path": "/a/b/c", "value": 42 },
   ]

Which should be the preferred way to remove data from an object?

**Comment by darrelmiller** [comment]
The PATCH method itself doesn't not define the details of how to actually achieve the PATCH.  That is by design.  The media types you have found are the two JSON based patch documents that provide these details.  Both are valid approaches.  Each have their strengths and weaknesses.  The second option is definitely the better option for removing things.

**Comment by maerlin** [comment]
Thank you for your answer! I thought it would be useful to mention this in the guidline, as there is only written about 'update' and 'add' (UPSERT).

Is there any special reason, why the second one is better for removing things?

**Comment by darrelmiller** [comment]
JSON-Patch has an explicit remove operation that can act on any part of the document using a JSON-Pointer.  JSON-Merge-Patch requires you to recreate the structure of the target document and use a null value to indicate removal of properties. What happens if null is a valid value for a property?

Removing elements in an array requires sending a copy of the array with the target element removed.  This can be less than idea if it is an array of objects.  To be honest, I haven't used JSON Merge patch much, but I have spent many hours trying to resolve issues around doing merge patching.  But I have written a .Net library for [JSON-Patch](https://github.com/tavis-software/Tavis.JsonPatch) so maybe I'm just biased :-)
