### ISSUE TITLE
Unsupported section is contradictory to HTTP status code 501

### ISSUE THREAD

**Issue by CoolDadTx** [Microsoft/api-guidelines#77]
The section on Unsupported says to return an error response and a 4xx result unless there is a more specific code. But that is what HTTP 501 is designed for in my opinion. If something is not supported then 501 is the correct response to let the client know they are trying to call something that is not implemented (but perhaps could be in the future).

**Comment by RobDolinMS** [comment]
Thanks for posting this issue @CoolDadTx 

For others who are likely wondering about HTTP 501, here's the reference in the HTTP 1.1 spec: http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.5.2

> 10.5.2 501 Not Implemented
> The server does not support the functionality required to fulfill the request. This is the appropriate response when the server does not recognize the request method and is not capable of supporting it for any resource.

**Comment by darrelmiller** [comment]
@CoolDadTx  I agree that it is confusing.  However, the 501 status code has the additional requirement that the functionality is not supported for any resource on the server.  Although that may be the case for some API scenarios, there are other cases where certain functionality is not supported on a particular set of resources.  

Requiring applications to sometimes return a 4XX code when there is partial support for a feature and 501 when there is none is an additional burden on the client.

Imagine also, if paging were not supported, and then at some point in the future it is added for just one resource.  Does that mean all other resource now have to start returning 4XX instead of 501?

The 501 response code is more useful for Web servers, proxies, caches and other intermediaries. The intent is to make application developers aware that some piece of infrastructure is preventing their server application from behaving correctly and it is up to the server application developer to fix the issue.

Applications themselves don't gain any benefits from returning 501, at least none that I'm aware of.

**Comment by gareth-a-jones** [comment]
I think this is fairly definitive from @darrelmiller
